language: java
jdk:
- oraclejdk8
sudo: false
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  email:
    on_success: always