DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES (
  UUID UUID NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  EMAIL VARCHAR(50),
  FIRSTNAME VARCHAR(60),
  LASTNAME VARCHAR(60),
  AVATAR VARCHAR(300),
  PHONE VARCHAR(15),
  UNIT VARCHAR(20),
  GENDER VARCHAR(20) DEFAULT 'MALE'
);

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
  ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS ROLE_ASSIGNMENTS;
CREATE TABLE ROLE_ASSIGNMENTS(
  EMPLOYEES_ID UUID NOT NULL,
  ROLES_ID BIGINT NOT NULL
);
ALTER TABLE ROLE_ASSIGNMENTS
  ADD CONSTRAINT EMPLOYEES_ROLES_PKEY PRIMARY KEY (EMPLOYEES_ID, ROLES_ID);
